name = "biolink-franco"
main = "src/index.ts"
compatibility_date = "2026-08-01"
routes = [{ pattern = "bio.francorafael.com", custom_domain = true }]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BIOLINK_DB"
id = "d8a4b8a570b645f29e598681181b5c0c"
